### ISSUE TITLE
Better CSS for standalone HTML

### ISSUE THREAD

**Issue by makeworld-the-better-one** [melmothx/amusewiki#365]
Hey, thanks for creating this great and unique project.

I was wondering if you would be open to changing the CSS for standalone HTML versions of pages, like [this](https://amusewiki.org/library/install.html). Right now it's difficult to read on a desktop device, because the text width is so wide. And on mobile, the width is fine, but the text size is small.

Are you open to changing this? And am I right in understanding this is controlled by the `t/custom-templates/html.tt` file? It seemed very similar but slightly different to the standalone on the site, but I assume that's just because you don't run master on there.

Here's a template I'm fond of:

```css
body {
    margin: 40px auto;
    max-width: 100%;
    line-height: 1.6;
    font-size: 18px;
    color: rgb(0, 0, 0);
    padding: 0 20px;
    word-wrap: break-word;
}

@media only screen and (min-width: 926px) {
    body {
        max-width: 45vw;
    }
}

h1, h2, h3{
    line-height: 1.2
}
```

I don't expect it to be perfect for your use case, but maybe something to go off of? This has nice text width for desktop and mobile, and a good text size.

Would be happy to hear suggestions on this, as I'm no CSS expert. Or intermediate.

**Comment by melmothx** [comment]
makeworld ***@***.***> writes:

> Hey, thanks for creating this great and unique project.
>
> I was wondering if you would be open to changing the CSS for
> standalone HTML versions of pages, like
> [this](https://amusewiki.org/library/install.html). Right now it's
> difficult to read on a desktop device, because the text width is so
> wide. And on mobile, the width is fine, but the text size is small.
>
> Are you open to changing this? And am I right in understanding this is
> controlled by the `t/custom-templates/html.tt` file? It seemed very
> similar but slightly different to the standalone on the site, but I
> assume that's just because you don't run master on there.

Hi and thanks for your interest in the project.

The `t/custom-templates/html.tt` file is just a test file, so it has no
effect, but yes, the standalone HTML version can be changed using
`html.tt`, and you need to place it in the right directory. See this
link for the details:

https://amusewiki.org/library/templates-and-formats#toc3

Please note that you have to rebuild the files after changing that
(admin menu, "Rebuild all generated files").

That said, we're talking about changing the default template, so the
right location for these changes would be here:

https://github.com/melmothx/text-amuse-compile/blob/521f88ffee33f3f9e3beb1687aa2d4245a11b6be/lib/Text/Amuse/Compile/Templates.pm#L217

The CSS is shared with the EPUB one, so these changes need to be html.tt
specific (after the CSS inclusion).

> Here's a template I'm fond of:
>
> ```css
> body {
>     margin: 40px auto;
>     max-width: 100%;
>     line-height: 1.6;
>     font-size: 18px;
>     color: rgb(0, 0, 0);
>     padding: 0 20px;
>     word-wrap: break-word;
> }
> @media only screen and (min-width: 926px) {
>     body {
>         max-width: 45vw;
>     }
> }

Here I'm wondering why not having the max-width at 860px instead, i.e.
the same width of the text before the media query kicks in?

Thoughts?

-- 
Marco

**Comment by makeworld-the-better-one** [comment]
> That said, we're talking about changing the default template, so the
right location for these changes would be here:


Oh I see the CSS in there now. Thanks.

> Here I'm wondering why not having the max-width at 860px instead, i.e.
the same width of the text before the media query kicks in?

You're right, the media query isn't necessary. The other problem I noticed is that using `vw` means that it can get weirdly wide on wider viewports. Better to keep it the same width everywhere with `px`. Here's the full new version of the CSS, I went with 720px.

```css
body {
    margin: 40px auto;
    max-width: 720px;
    line-height: 1.6;
    font-size: 18px;
    color: rgb(0, 0, 0);
    padding: 0 20px;
    word-wrap: break-word;
    font-family: Sans-Serif;
}

h1, h2, h3{
    line-height: 1.2
}
```
